name: GitHub IaC

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      apply:
        description: Should the plan also be applied?
        type: boolean
        required: true
        default: false
  repository_dispatch:
    types:
      - addons-update
  push:
    branches:
      - main
    paths:
      - github-iac

jobs:
  plan:
    name: 📝 Plan IaC changes
    runs-on: ubuntu-latest
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v6

      - name: 🏗️ Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: ⤵️ Download latest addons.yml file from stable repository
        uses: enflo/curl-action@v1
        with:
          curl: -o addons.yml https://raw.githubusercontent.com/Poeschl-HomeAssistant-Addons/repository/refs/heads/main/.addons.yml

      - name: 👀 View addons config
        run: cat addons.yml

      - name: 🏗️ Terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.IAC_TOKEN }}
        run: cd github-iac && terraform init

      - name: 📝 Terraform plan
        id: plan
        env:
          GITHUB_TOKEN: ${{ secrets.IAC_TOKEN }}
        run: cd github-iac && terraform plan -out plan.out

      - name: ⤴️ Upload plan
        uses: actions/upload-artifact@v6
        with:
          name: github-iac-artifact
          path: github-iac/plan.out

  apply:
    name: 🚀 Apply IaC changes
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply == 'true'
    needs:
      - plan
    steps:
      - name: ↩️ Checkout
        uses: actions/checkout@v6

      - name: 🏗️ Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: ⤵️ Get plan artifact
        uses: actions/download-artifact@v7
        with:
          name: github-iac-artifact
          path: github-iac

      - name: ⤵️ Download latest addons.yml file from stable repository
        uses: enflo/curl-action@v1
        with:
          curl: -o addons.yml https://raw.githubusercontent.com/Poeschl-HomeAssistant-Addons/repository/refs/heads/main/.addons.yml

      - name: 🏗️ Terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.IAC_TOKEN }}
        run: cd github-iac && terraform init

      - name: 🚀 Apply plan
        env:
          GITHUB_TOKEN: ${{ secrets.IAC_TOKEN }}
        run: cd github-iac && terraform apply -auto-approve plan.out
